version: "3.7"
services:
  db_1:
    image: postgres:11
    environment:
      POSTGRES_USER: experiment
      POSTGRES_PASSWORD: experiment
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - default
  db_2:
    image: postgres:11
    environment:
      POSTGRES_USER: experiment
      POSTGRES_PASSWORD: experiment
    expose:
      - "5432"
    ports:
      - "5433:5432"
    networks:
      - default
networks:
  default: {}